import { query } from "@anthropic-ai/claude-agent-sdk";
import { desc, eq } from "drizzle-orm";
import { getDb, agentRuns, runEvents, type AgentRun, type Task } from "@/db";

// Pull the agent's own final summary (the `result` message text) for the
// task's most recent completed run.
export function latestRunSummary(taskId: number): { summary: string; run: AgentRun | null } {
  const db = getDb();
  const run = db
    .select()
    .from(agentRuns)
    .where(eq(agentRuns.taskId, taskId))
    .orderBy(desc(agentRuns.id))
    .limit(1)
    .get();
  if (!run) return { summary: "", run: null };
  const resultEvent = db
    .select()
    .from(runEvents)
    .where(eq(runEvents.runId, run.id))
    .orderBy(desc(runEvents.seq))
    .all()
    .find((e) => e.eventType === "result");
  let summary = "";
  if (resultEvent) {
    try {
      const payload = JSON.parse(resultEvent.payload) as { result?: string };
      summary = typeof payload.result === "string" ? payload.result : "";
    } catch {
      summary = "";
    }
  }
  return { summary, run };
}

// Generates the "Why" and "Impact on stakeholders" prose via a one-shot,
// tool-less model call. Returns null on any failure so the caller can fall
// back to a body without these sections rather than blocking the PR.
async function generateNarrative(opts: {
  task: Task;
  summary: string;
  diffStat: string;
}): Promise<{ why: string; impact: string } | null> {
  const prompt = [
    "You are writing two short sections of a pull request description. Base them ONLY on the information below — do not invent features or claims not supported by it.",
    "",
    `Task type: ${opts.task.type}`,
    `Task title: ${opts.task.title}`,
    `Task brief:\n${opts.task.description}`,
    "",
    opts.summary ? `What the agent reported doing:\n${opts.summary}` : "",
    "",
    `Files changed:\n${opts.diffStat || "(not available)"}`,
    "",
    "Output EXACTLY this format, nothing else:",
    "WHY: <2-3 sentences on why this change is needed / the problem it solves>",
    "IMPACT: <2-3 sentences on who is affected and how — end users, maintainers, downstream consumers>",
  ]
    .filter(Boolean)
    .join("\n");

  try {
    let text = "";
    const q = query({
      prompt,
      options: {
        model: opts.task.model,
        allowedTools: [],
        maxTurns: 1,
        permissionMode: "bypassPermissions",
      },
    });
    const timeout = setTimeout(() => q.close(), 60000);
    try {
      for await (const message of q) {
        if (message.type === "assistant" && Array.isArray(message.message?.content)) {
          for (const block of message.message.content) {
            if (block.type === "text") text += block.text;
          }
        }
      }
    } finally {
      clearTimeout(timeout);
    }

    const why = text.match(/WHY:\s*([\s\S]*?)(?:\nIMPACT:|$)/i)?.[1]?.trim();
    const impact = text.match(/IMPACT:\s*([\s\S]*)/i)?.[1]?.trim();
    if (!why && !impact) return null;
    return { why: why ?? "", impact: impact ?? "" };
  } catch {
    return null;
  }
}

// Assembles the full PR body: generated Why/Impact on top, then deterministic
// sections from data we already have.
export async function buildPrBody(opts: {
  task: Task;
  summary: string;
  diffStat: string;
  testStatus: string | null;
  testOutput: string | null;
}): Promise<string> {
  const { task, summary, diffStat, testStatus, testOutput } = opts;
  const parts: string[] = [];

  if (summary.trim()) parts.push(`## Summary\n\n${summary.trim()}`);

  const narrative = await generateNarrative({ task, summary, diffStat });
  if (narrative?.why) parts.push(`## Why\n\n${narrative.why}`);
  if (narrative?.impact) parts.push(`## Impact on stakeholders\n\n${narrative.impact}`);

  if (diffStat.trim()) {
    parts.push(`## Changes\n\n\`\`\`\n${diffStat.trim()}\n\`\`\``);
  }

  if (testStatus && testStatus !== "skipped") {
    const icon = testStatus === "passed" ? "✅ passed" : "❌ failed";
    let section = `## Testing\n\nRepository test command: **${icon}**`;
    if (testStatus === "failed" && testOutput) {
      section += `\n\n<details><summary>output</summary>\n\n\`\`\`\n${testOutput.slice(-4000)}\n\`\`\`\n\n</details>`;
    }
    parts.push(section);
  }

  parts.push(`## Task brief\n\n${task.description.trim()}`);
  parts.push(`---\n🤖 Generated by an agent run in git-dashboard.`);

  return parts.join("\n\n");
}
